#ResNet.yaml

resnet:
    _target_: ecg_classifier.module.ResNetMeta
    block: ecg_classifier.module.BasicBlock
    layers: [2, 2, 2, 2]
    in_channels: 12
    num_classes: 4
    drop_prob_head: 0.25
    drop_prob_backbone: 0.1
    in_channels_meta: 5
    drop_prob_meta: 0.25

train:
    batch_size: 64
    learning_rate: 0.0005
    n_epoch: 30