# ds.yaml

_target_: ecg_classifier.data.ECGDataset
target_labels: {
      'arrit': ['SARRH', 'SVARR'],
      'tach': ['STACH', 'SVATC', 'PSVT'],
      'brad': ['SBRAD'],
      'afib': ['AFIB', 'AFLT']
  }
path: "dataset/physionet.org/files/ptb-xl/1.0.1/"
sampling_rate: 100
use_metadata: False
use_pqrst: False