# configs/config.yaml

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${model.name}_afib_${now:%H-%M-%S}
  job:
    chdir: True
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${model.name}_afib_${now:%H-%M-%S}

defaults:
  - dataset: ds
  - model: model
  - optimizer: adam
  - criterion: cr
  - scheduler: scheduler
  - early_stopping: es
