# configs/config.yaml

defaults:
  - dataset: ds
  - model: resnet
  - optimizer: adam
  - criterion: cr
  - scheduler: scheduler

train:
    batch_size: 64
    learning_rate: 0.005
    n_epoch: 60
    drop_prob_head: 0.3
    drop_prob_backbone: 0.1

early_stopping:
    patience: 7
