# configs/config.yaml

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${model.name}_${dataset.target_labels}_${now:%H-%M-%S}
  job:
    chdir: True

defaults:
  - dataset: ds
  - model: model
  - optimizer: adam
  - criterion: cr
  - scheduler: scheduler
  - early_stopping: es
